idam_api_url = "https://idam-api.demo.platform.hmcts.net"
capacity = "2"
frontend_url = "https://www.ccd.demo.platform.hmcts.net"
asp_name = "ccd-definition-designer-api-demo"
asp_rg = "ccd-definition-designer-api-demo"
elastic_search_enabled = "true"
elastic_search_fail_on_import = "true"
